# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box_check_update = true
  config.ssh.insert_key = false
  config.ssh.keys_only = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.forward_agent = true

  config.vm.define :jenkins do |vm0|
    vm0.vm.box = "centos/7"
    vm0.vm.host_name = "jenkins"
    vm0.vm.provider "virtualbox" do |vb|
      vb.name = "vm0-jenkins"
      vb.memory = "2048"
      vb.cpus = 2
    end
    vm0.vm.network "private_network", type: "dhcp"
#    vm0.vm.network "hostonly", vboxnet0
    vm0.vm.network "forwarded_port", guest: 8080, host: 8080
#    vm0.vm.network "forwarded_port", guest: 10050, host: 10050
    vm0.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    vm0.vm.provision "shell", inline: "yum update -y"
  end

  config.vm.define "gitlab-ce" do |vm1|
    vm1.vm.box = "centos/7"
    vm1.vm.hostname = "gitlab-ce"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1-gitlab"
      vb.memory = "1024"
    end
    vm1.vm.network "private_network", type: "dhcp"
    vm1.vm.network "forwarded_port", guest: 80, host: 8800
#    vm1.vm.network "forwarded_port", guest: 8081, host: 8081
    vm1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    vm1.vm.provision "shell", inline: "yum update -y"
  end

  config.vm.define :zabbix-srv do |vm2|
    vm2.vm.box = "centos/7"
    vm2.vm.host_name = "zabbix"
    vm2.vm.network "private_network", type: "dhcp"
#    vm2.vm.network "forwarded_port", guest: 8080, host: 8081
#    vm2_config.vm.network "forwarded_port", guest: 10051, host: 10051
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "vm2-zabbix"
      vb.memory = "1024"
    end
    vm2.vm.provision "shell", inline: "yum update -y"
  end

end

