# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.ssh.forward_agent = true
  config.vm.define :build_vm0 do |vm0|
    vm0.vm.box = "centos/7"
    vm0.vm.box = "jenkins"
    vm0.vm.network "private_network", type: "dhcp"
    config.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
    end
#    vm0_config.vm.network = hostonly, vboxnet0
    vm0.vm.network "forwarded_port", guest: 8080, host: 8080
    vm0.vm.network "forwarded_port", guest: 10050, host: 10050
    vm0.vm.provision "shell",
      inline: "yum update -y
      yum install wget -y
      wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
      rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
      rpm -ivh http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
      yum install java-1.7.0-openjdk jenkins -y
      service jenkins start"
  end

#  config.vm.define :build_vm1 do |vm1_config|
#    vm1_config.vm.box = "centos/7"
#    vm1_config.vm.box = "vm1"
#    vm1_config.vm.network "private_network", type: "dhcp"
#    vm1_config.vm.network "forwarded_port", guest: 8080, host: 8082
#    vm1_config.vm.network "forwarded_port", guest: 8081, host: 8081
#  end

  config.vm.define :build_vm2 do |vm2_config|
    vm2_config.vm.box = "centos/7"
    vm2_config.vm.box = "vm2"
    vm2_config.vm.network "private_network", type: "dhcp"
    vm2_config.vm.network "forwarded_port", guest: 8081, host: 8081
    config.vm.provider "virtualbox" do |vb|
        # Customize the amount of memory on the VM:
        vb.memory = "1024"
    end

    vm2_config.vm.provision "shell",
      inline: "yum update -y
      yum install java-1.7.0.openjdk wget -y
      rpm -ivh http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
      yum install zabbix-server-mysql zabbix-web-mysql -y"
  end
end

