# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box_check_update = true
  config.ssh.insert_key = false
  config.ssh.keys_only = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.forward_agent = true

  config.vm.define :jenkins do |vm0|
    vm0.vm.box = "centos/7"
    vm0.vm.host_name = "jenkins"
    vm0.vm.provider "virtualbox" do |vb|
      vb.name = "vm0-jenkins"
      vb.memory = "2048"
      vb.cpus = 2
    end
    vm0.vm.network "private_network", type: "dhcp"
    vm0.vm.network "forwarded_port", guest: 8080, host: 8080
    vm0.vm.network "forwarded_port", guest: 8081, host: 8081
#    vm0.vm.network "forwarded_port", guest: 10050, host: 10050
    vm0.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
#    vm0.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
    vm0.vm.provision "file", source: "~/.ssh/jenkins_rsa", destination: "~/.ssh/jenkins_rsa"
    vm0.vm.provision "file", source: "../jenkins", destination: "/var/lib/"
    vm0.vm.provision "shell", path: "provision.sh"
  end

  config.vm.define "gitlab-ce" do |vm1|
    vm1.vm.box = "centos/7"
    vm1.vm.hostname = "gitlab-ce"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1-gitlab"
      vb.memory = "1024"
    end
    vm1.vm.network "private_network", type: "dhcp"
    vm1.vm.network "forwarded_port", guest: 80, host: 8800
    vm1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
#    vm1.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
    vm1.vm.provision "file", source: "~/.ssh/jenkins_rsa", destination: "~/.ssh/jenkins_rsa"
    vm1.vm.provision "shell", path: "provision.sh"
  end

  config.vm.define :zabbix do |vm2|
    vm2.vm.box = "centos/7"
    vm2.vm.host_name = "zabbix-srv"
    vm2.vm.network "private_network", type: "dhcp"
    vm2.vm.network "forwarded_port", guest: 8080, host: 8880
    vm2.vm.network "forwarded_port", guest: 10050, host: 10050
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "vm2-zabbix"
    end
    vm2.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
#    vm2.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
    vm2.vm.provision "file", source: "~/.ssh/jenkins_rsa", destination: "~/.ssh/jenkins_rsa"
    vm2.vm.provision "shell", path: "provision.sh"
  end

  config.vm.define :ansibletower do |vm3|
    vm3.vm.box = "ansible/tower"
    vm3.vm.hostname = "ansible-twr"
    vm3.vm.network "private_network", type: "dhcp"
    vm3.vm.network "forwarded_port", guest: 8080, host: 8888
    vm3.vm.provider "virtualbox" do |vb|
      vb.name = "ansible-twr"
    end
    vm3.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    vm3.vm.provision "shell", path: "provision.sh"
  end

end
