---
- name: Install packeges
  yum: name={{ item }} state=latest
  with_items:
  - wget
  - git
  - unzip

- name: Get artifactory
  get_url:
    url: 
    dest: /var/lib/artifactory

- name: Install Artifactory
  shell: ./artifactory.sh

- name: Enable Artifactory
  shell: ./installService.sh