---

- name: Import Zabbix key
  rpm_key:
    key: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
    state: present
    validate_certs: no

- name: repo
  copy: src=files/zabbix.repo
    dest=/etc/yum.repos.d/
    owner=root group=root mode=0644

- name: Update SELinux yum packages to latest
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - selinux-policy
    - policycoreutils
    - selinux-policy-targeted
    - policycoreutils-python
    - polkit

- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
#    - unixODBC
    - libtool-ltdl
    - zabbix-agent
#    - zabbix-sender
#    - zabbix-get


- name: copy configuration file
  copy:
    src=files/zabbix_agentd.conf
    dest=/etc/zabbix/zabbix_agentd.conf
    owner=root group=root mode=0644

- name: Start firewalld service
  service:
     name: firewalld
     state: started
     enabled: yes

- name: Opening port 10050
  firewalld: port=10050/tcp permanent=true state=enabled

- name: Run Zabbix Agent on boot
  service:
    name: zabbix-agent
    state: started
    enabled: yes
  notify:
    - restart zabbix-agent