---

- name: Import Zabbix key
  rpm_key:
    key: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
    state: present
    validate_certs: no

- name: Set Zabbix repo
  copy: src=files/zabbix.repo
    dest=/etc/yum.repos.d/
    owner=root group=root mode=0644

- name: Install Zabbix-agent
  yum:
    name: zabbix-agent
    state: present


- name: Copy configuration file
  copy:
    src=files/zabbix_agentd.conf
    dest=/etc/zabbix/zabbix_agentd.conf
    owner=zabbix group=zabbix mode=0644

- name: Craete Folder
  file: path=/run/zabbix/ owner=zabbix group=zabbix mode=0755 state=directory

- name: Run Zabbix Agent on boot
  service:
    name: zabbix-agent
    state: started
    enabled: yes
  notify:
    - restart zabbix-agent

